config/routes.rb
Rails.application.routes.draw do
  root 'freelancers#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  match 'logout' => 'sessions#destroy', via: [:get, :delete]
  post 'signup' => 'users#create'

  resources :users, only: [:edit, :update, :show]
  resources :email_confirmations, only: [:show, :index]
  resources :password_reset, only: [:show, :update, :create]
  resources :ratings, only: [:create, :show]


  get 'bookings/index'
  post 'bookings/create'






  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :freelancers, only: [:show, :new, :update, :edit, :create, :index], as: 'profile' do |f|
    resources :enquiries, only: [:new]
  end

  # resources :freelancers, only: [:show, :new, :update, :edit, :create, :index], as: 'restricted' do |f|
  #   resources :booking
  # end


  resources :enquiries,except: [:new]
  resources :ratings, only: [:show,:create]


  mount ActionCable.server, at: '/cable'


end

app/models/freelancer.rb
class Freelancer < ApplicationRecord
  # ASSOCIATIONS (ANDREW)
  belongs_to :user
  has_many :enquiries, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :ratings,  dependent: :destroy

  # BOOKABLE GEM (ANDREW)
  acts_as_bookable time_type: :range, bookable_across_occurrences: true

  validates :user_id, uniqueness: true

  before_save :downcase_description_profression
  before_update :downcase_description_profression
  after_validation :convert_to_utc, :if => :working_hours_set

  def self.search(search)
    if search
      where('profession ILIKE ?', "%#{search}%")
    else
      all
    end
  end

  def convert_to_utc
    @freelancer = Freelancer.find_by_id(id)
    @freelancer.start_working_hours = @freelancer.start_working_hours.to_time.utc
    @freelancer.end_working_hours = @freelancer.end_working_hours.to_time.utc
  end

  private

  def downcase_description_profression
    self.description = self.description.downcase
    self.profession = self.profession.downcase
  end

  def working_hours_set
    @freelancer = Freelancer.find_by_id(id)
    if @freelancer
      if @freelancer.start_working_hours && @freelancer.end_working_hours
        return true
      else
        return false
      end
    else
      return false
    end
  end
end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController
  include FreelancersHelper

  before_action :check_user, except: [:index, :show]
  before_action :is_freelancer?, except: [:index,:new, :create]


  def new
    if Freelancer.find_by(user_id: current_user[:id])
      redirect_to profile_index_path
    end
    puts current_user.name
    @freelancer = Freelancer.new
  end

  def index
    @freelancers = Freelancer.search(params[:search])
  end

  def show
    @freelancer = Freelancer.find_by(id: params[:id])
    @bookings = @freelancer.bookings
    @enquiry = Enquiry.new
    # not clean could refactor into function ZL
    if @freelancer.ratings.average('professionalism').is_a? Numeric
      @compiled_rating = ( @freelancer.ratings.average('professionalism') +
                            @freelancer.ratings.average('value') +
                            @freelancer.ratings.average('cleanliness') ) / 3
      @rating_professionalism = @freelancer.ratings.average('professionalism')
      @rating_value = @freelancer.ratings.average('value')
      @rating_cleanliness = @freelancer.ratings.average('cleanliness')
      @first_3_reviews = @freelancer.ratings.order(created_at: :desc).limit(3)
    else
      @compiled_rating = nil
      @first_3_reviews = nil
    end

    @enquiries = Enquiry.all.where(freelancer_id: params[:id]).where(status: 'open').order(:created_at)
    @own_enquiries = Enquiry.all.where(user_id: params[:id]).where(status: 'open').order(:start_date)
    # @accepted_enquires = Enquiry.all.where(freelancer_id: params[:id]).where(status: 'accepted').order(:start_date)

    @sanitized_start_time = @freelancer.schedule.start_time.strftime("%I:%M%p")
    @sanitized_end_time = @freelancer.schedule.end_time.strftime("%I:%M%p")

    #might be able to do something cool with this
    @bookings_grped_by_date = @freelancer.bookings.order("date(time_start)").group("date(time_start)").count
    @first_booking_grped_by_date = @freelancer.bookings.limit(1).order("date(time_start)").group("date(time_start)").count

    #### YOU STOPPED HERE ZL
    ## done
    @occurrences = {
      dates: @freelancer.schedule.occurrences_between(Date.today - 1.year,Date.today + 1.year),
      start_time: @sanitized_start_time,
      end_time: @sanitized_end_time,
    }
  end

  def edit
    @freelancer = Freelancer.find_by(id: params[:id])
    # IF RECCURENCE RULE NOT 0
    if @freelancer.schedule.rrules.length != 0
      @freelancer_days = integer_to_date(@freelancer.schedule.to_hash[:rrules][0][:validations][:day])
    else
      # SET FREELANCER_DAYS TO MONDAY IF NO RECCURENCE SET
      @freelancer_days = integer_to_date([1])
    end
  end

  #CAPACITY IS THROWING AN ERROR for now
  def update
    @freelancer = Freelancer.find_by(id: params[:id])
      upload_picture
    @address = @freelancer.address
    if @address.blank?
      @freelancer.latitude = 0
      @freelancer.longitude = 0
    else
      response = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{@address}&key=AIzaSyBCTtS1KnxXuh22lty2vDgBn54QlfhiVKM", verify: false)
      parsed_json = JSON.parse(response.body)
      puts "response is #{parsed_json}"
      @freelancer.latitude= parsed_json["results"][0]['geometry']['location']['lat']
      @freelancer.longitude= parsed_json["results"][0]['geometry']['location']['lng']
    end
    # HELPER FUNCTION -> DELETE PRE RECURRENCES
    delete_recurrence_rule(@freelancer)
    # SAVE AFTER REMOVE RULE

    @freelancer.save
    @freelancer.user.update(profile_picture: @freelancer.picture)
    if @freelancer.update(freelancer_params)
      # HELPER FUNCTION -> UPDATE SCHEDULE COLUMN
      fl_schedule_column(@freelancer)
      # SAVE AFTER UPDATE COLUMN
      @freelancer.save
      # HELPER FUNCTION -> UPDATE DAILY RECURRENCE
      if params[:days]
        recurrence_rule(@freelancer)
        # SAVE AFTER UPDATE COLUMN
        @freelancer.save
      end

      flash[:success] = 'updated profile!'
      redirect_to profile_path(@freelancer.id)
    else
      flash[:danger] = 'unable to update profile'
      render :edit
    end
  end

  def create
    @freelancer = Freelancer.new(freelancer_params)
    @freelancer.user_id = current_user[:id]
    @address = @freelancer.address
    response = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{@address}&key=AIzaSyBCTtS1KnxXuh22lty2vDgBn54QlfhiVKM", verify: false)
    parsed_json = JSON.parse(response.body)
    puts "response is #{parsed_json}"
    @freelancer.latitude= parsed_json["results"][0]['geometry']['location']['lat']
    @freelancer.longitude= parsed_json["results"][0]['geometry']['location']['lng']
    # HELPER FUNCTION -> CREATE FREELANCER SCHEDULE COLUMN
    fl_schedule_column(@freelancer)
    # HELPER FUNCTION -> UPDATE DAILY RECURRENCE
    if params[:days]
      recurrence_rule(@freelancer)
    end

    if @freelancer.save!
      flash[:success] = 'created a profile!'
      redirect_to profile_path(@freelancer.user_id)
    else
      flash[:danger] = 'something went wrong'
      render 'new'
    end
  end

  private
    def freelancer_params
      params.require(:freelancer).permit(
        :profession,
        :address,
        :latitude,
        :longitude,
        :experience,
        :description,
        :picture,
        :start_working_hours,
        :end_working_hours,
        :price_start,
        :price_end,
        :days)
    end

    def check_user
      if !current_user
        flash[:danger] = 'Please login in to use the service!'
        redirect_to login_path
      end
    end

    def is_freelancer?
      if !Freelancer.find_by(id: params[:id])
        redirect_to profile_index_path
      end
    end


  def upload_picture
   if params[:freelancer][:picture] != nil
     if @freelancer.valid?
       uploaded_file = params[:freelancer][:picture].path
       puts "PATH #{uploaded_file}"
       cloudnary_file = Cloudinary::Uploader.upload(uploaded_file)
       @freelancer.picture = cloudnary_file['public_id']
     else
       cloudnary_file = Cloudinary::Uploader.upload("../assets/images/default.png")
       @freelancer.picture = cloudnary_file['public_id']
     end
     params[:freelancer].delete :picture
   end
  end
end

app/helpers/freelancers_helper.rb
module FreelancersHelper
  def local_time_scrub(datetime)
    datetime.in_time_zone("Singapore").to_time
  end

  def print_working_hours(start_t, end_t)
    puts start_t
    puts end_t
  end

  def fl_schedule_column(freelancer)
    # FIND START AND END WORKING HOURS
    @fl_start_time = freelancer.start_working_hours.to_time
    @fl_end_time = freelancer.end_working_hours.to_time
    # PRINT BOTH START AND END
    print_working_hours(@fl_start_time, @fl_end_time)
    # SET DURATION OF WORKING HOURS
    @duration = (((@fl_start_time - @fl_end_time) / 1.hour).round).abs
    puts @duration
    # SET FREELANCER SCHEDULE
    freelancer.schedule = IceCube::Schedule.new(@fl_start_time, duration: @duration.hours)
  end

  def string_to_symbol_scrub(array)
    day_arr = []
    array.each do | day |
      day = day.downcase.to_sym
      day_arr << day
    end
    day_arr
  end

  def recurrence_rule(freelancer)
    # SCRUB STRING TO SYMBOLS
    scrubbed_days = string_to_symbol_scrub(params[:days])
    # ADDING RECURRENCE TO ICE_CUBE SCHEDULING
    freelancer.schedule.add_recurrence_rule IceCube::Rule.weekly.day(scrubbed_days)
  end

  def integer_to_date(arr)
    res = []
    # SETTING EACH NUMBER TO DAY NAMES E.G "SUNDAY"
    arr.each do | number |
      res << Date::DAYNAMES[number]
    end
    res
  end

  def delete_recurrence_rule(freelancer)
    # FIRST RECURRENCE IN SCHEDULE VALIDATION
    freelancer_schedule_validation = freelancer.schedule.rrules.shift
    # DELETE RECURRENCE IN ICE_CUBE SCHEDULE RULE
    freelancer.schedule.remove_recurrence_rule(freelancer_schedule_validation)
  end

  def compiled_rating(freelancer)
    if freelancer.ratings.average('professionalism').is_a? Numeric
      result = (freelancer.ratings.average('professionalism') +
                          freelancer.ratings.average('value') +
                          freelancer.ratings.average('cleanliness') ) / 3
    else
      result = nil
    end
    return result
  end
end

app/views/freelancers/partials/_map.html.erb
<div id="map"></div>


<script>
function initMap() {
  console.log("entered")
  var uluru = {lat: 1.3521, lng: 103.8198};
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 12,
    center: uluru
  });

  var infoWindow = new google.maps.InfoWindow({map: map});
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            infoWindow.setPosition(pos);
            infoWindow.setContent('Location found.');
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          handleLocationError(false, infoWindow, map.getCenter());
        }


      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
      }

  <% @freelancers.each do |freelancer| %>
  <% if !freelancer.latitude.blank? && !freelancer.longitude.blank? %>

  var marker = new google.maps.Marker({
    position: {lat: <%=freelancer.latitude%>, lng: <%=freelancer.longitude%>},
    url: '<%= profile_path(freelancer) %>',
    map: map
  });
  var infowindow = new google.maps.InfoWindow();
  marker.addListener('click', function() {
    console.log('entered')
    infowindow.open(map, this);
    infowindow.setContent('<p><%= freelancer.profession%></p><br><a href="<%= profile_path(freelancer) %>">Book</a>')
  });

  <% end %>
  <% end %>
}
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBCTtS1KnxXuh22lty2vDgBn54QlfhiVKM&callback=initMap&libraries=geometry">
</script>

app/views/freelancers/partials/_show_dashboard.html.erb
<div class='container'>
<div class='row'>
<%= render 'partials/search' %>
<div class='placeholder_box'>
  <div class='left'>
    <div class='picture_freelancer'>
        <%if !@freelancer.picture%>
        <%= cl_image_tag('https://www.soundstream.tv/assets/default_profile-e08597880fc222202f22984a4f1966a29b108e856a3fb935072bfbbc302a4b73.png')%>
        <% else %>
        <%= cl_image_tag(@freelancer.picture,
            :width => 400, :height => 400, :default_image => "avatar.png")
            %>
            <% end %>
      </div>

    <div class='current_reviews_limit_3'>
      <h3>Current Overall Rating</h3>
      <%= render partial: 'partials/form_for_ratings', locals: {big_rating: @compiled_rating} %>
      <br>
      <h3>Latest reviews from other users</h3>
      <% if @first_3_reviews %>
        <% @first_3_reviews.each do |review| %>
          <p><%= review.user.name%> said: <%= review.description_of_job %></p>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class='right'>
    <div class='pending_enquires, well'>
      <%= render 'freelancers/partials/show_pending_enquiries_from_others' %>
    </div>

    <div class ='own_calendar, well'>
      <h2>Your Schedule for the month</h2>

      <h5>
        You work <%= @freelancer.schedule.to_s.downcase %> from
        <%= @occurrences[:start_time] %> to
        <%= @occurrences[:end_time] %>
      </h5>

      <h3>Edit your profile to change your schedule</h3>
      <%= month_calendar(partial: 'simple_calendar/month_calendar', events: @occurrences[:dates] ) do |date, occurrences| %>
        <%= date.day %>
        <% @freelancer.bookings.each do |booking| %>
          <% if date == booking.time_start.to_date %>
            <!-- slightly wrong pls edit in GA ZL slot is not pointing to correct enquiry path (should be finsihed enquiry no edits) -->
          <%= link_to enquiry_path(booking.booker.id) do %>
            <p class='slot'>Slot booked from <%= booking.time_start.strftime("%I:%M%p") %> to <%= booking.time_end.strftime("%I:%M%p") %>  </p>
          <% end %>

          <% end %>
        <% end %>
        <% occurrences.each do |occurrence| %>
        <p class='free'>
          Available from <%= @occurrences[:start_time] %> to <%= @occurrences[:end_time] %>
        </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/freelancers/partials/_show_own_enquiries_for_freelancer.html.erb
<h3>Submitted enquiries(My enquiries)</h3>
<table class="table">
  <% @own_enquiries.each do |enquiry| %>
    <tr>
      <td><%= enquiry.description %></td>
      <td><%= enquiry.start_date.to_time %></td>
      <td><%= enquiry.end_date.to_time %></td>
      <td><%= link_to "Chat with #{enquiry.freelancer.user.name.capitalize}", edit_enquiry_path(enquiry.id)%></td>
    </tr>
  <% end %>
</table>
<br>

app/views/freelancers/partials/_show_pending_enquiries_from_others.html.erb
<h3>Pending enquires</h3>
<table class='table'>
  <thead>
    <tr>
      <th>Description of Enquiry</th>
      <th>Enquiry's start date</th>
      <th>Enquiry's end date</th>
      <th>Liason</th>
    </tr>
  </thead>
  <% @enquiries.each do |enquiry| %>
    <% if enquiry.freelancer_id == current_freelancer.id %>
      <tr>
        <td><%=enquiry.description%></td>
        <td><%=enquiry.start_date.strftime("%e %b %Y %l:%M %p")%></td>
        <td><%=enquiry.end_date.strftime("%e %b %Y %l:%M %p")%></td>
        <td><%= link_to 'continue liason with customer', edit_enquiry_path(enquiry.id), {:class => 'btn btn-default'} %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/freelancers/partials/_show_profile.html.erb
  <div class="container">
    <div class='row'>
      <%= render 'partials/search' %>
    <div class="col-md-6">
      <div class='col-md-12 text-center'>
        <%if !@freelancer.picture%>
        <%= cl_image_tag('https://www.soundstream.tv/assets/default_profile-e08597880fc222202f22984a4f1966a29b108e856a3fb935072bfbbc302a4b73.png')%>
        <% else %>
        <%= cl_image_tag(@freelancer.picture,
            :width => 400, :height => 400, :default_image => "avatar.png")
            %>
            <% end %>
      </div>
      <br>
      <div class='col-md-12'>
        <h3><%= @freelancer.profession %></h3>
        <div class='col-md-4'>
          <h2><%= @freelancer.user.name.capitalize %></h2>
          <span>Overall</span>
            <%= render partial: 'partials/form_for_ratings', locals: {big_rating: @compiled_rating} %><br><br>
      <span>Professionalism</span>
      <%= render partial: 'partials/form_for_ratings', locals: {big_rating: @rating_professionalism} %><br><br>
      <span>Cleanliness</span>
      <%= render partial: 'partials/form_for_ratings', locals: {big_rating: @rating_cleanliness} %><br><br>
      <span>Value for money</span>
      <%= render partial: 'partials/form_for_ratings', locals: {big_rating: @rating_value} %><br><br>

        <% if current_user %>
          <% if Enquiry.where(user_id: current_user[:id], freelancer_id: @freelancer.id).size > 0 %>
            <%= link_to 'Click here to rate me!', rating_path %>
          <% end %>
        <% end %>
            </div>
        <div class='col-md-8'>
          <div class='col-md-12 '>
            <p class='description'> <%= @freelancer.description %></p>
            <p> $$ <%= @freelancer.price_start %> to <%= @freelancer.price_end %></p>
          </div>
        </div>
      </div>

</div>


  <div class='col-md-6 side-line'>
    <div class='col-md-12'>
    <div class="calendar-small">
      <%= month_calendar(partial: 'simple_calendar/month_calendar', events: @occurrences[:dates]) do |date, occurrences| %>
      <%= date.day %>
      <% occurrences.each do |occurrence| %>
      <div>
        Available from <%= @occurrences[:start_time] %> to <%= @occurrences[:end_time] %>
      </div>
      <% end %>
    <% end %>
    </div>
  </div>

  <div class='new_enquiry col-md-12'>
      <% if current_user %>
        <%= render 'enquiries/new' %><br>
      <% else %>
        <div class="btn btn-default text-white"><%= link_to "Login/Signup to make an enquiry", login_path %></div>
      <% end %>
  </div>

</div>
  </div>