config/routes.rb
Rails.application.routes.draw do
  root 'freelancers#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  match 'logout' => 'sessions#destroy', via: [:get, :delete]
  post 'signup' => 'users#create'

  resources :users, only: [:edit, :update, :show]
  resources :email_confirmations, only: [:show, :index]
  resources :password_reset, only: [:show, :update, :create]
  resources :ratings, only: [:create, :show]


  get 'bookings/index'
  post 'bookings/create'






  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :freelancers, only: [:show, :new, :update, :edit, :create, :index], as: 'profile' do |f|
    resources :enquiries, only: [:new]
  end

  # resources :freelancers, only: [:show, :new, :update, :edit, :create, :index], as: 'restricted' do |f|
  #   resources :booking
  # end


  resources :enquiries,except: [:new]
  resources :ratings, only: [:show,:create]


  mount ActionCable.server, at: '/cable'


end

app/views/partials/_calendar_for_specific_booking.html.erb
<%= week_calendar( start_date: passed_datum[:start_date] , partial: 'simple_calendar/week_calendar', events: passed_datum[:dates] ) do |date, occurrences| %>
  <%= date.day %>
  <% occurrences.each do |occurrence| %>
  <div>
    Available from <%= passed_datum[:start_time] %> to <%= passed_datum[:end_time] %>
  </div>
  <% end %>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/partials/_form_for_3_ratings.html.erb
<%= form_for :rating, url: ratings_path, html: { method: :post } do |f| %>
  <h4>Professionalism</h4>
  <fieldset class="rating">
    <%= f.radio_button(:professionalism, "5") %> <%= f.label(:professionalism.to_s + "_5", "Rocks") %>
    <%= f.radio_button(:professionalism, "4") %> <%= f.label(:professionalism.to_s + "_4", "Pretty good") %>
    <%= f.radio_button(:professionalism, "3") %> <%= f.label(:professionalism.to_s + "_3", "Meh") %>
    <%= f.radio_button(:professionalism, "2") %> <%= f.label(:professionalism.to_s + "_2", "Kinda bad") %>
    <%= f.radio_button(:professionalism, "1") %> <%= f.label(:professionalism.to_s + "_1", "Sucks big time") %>
  </fieldset>
  <br><br>

  <h4>Value for money</h4>
  <fieldset class="rating">
    <%= f.radio_button(:value, "5") %> <%= f.label(:value.to_s + "_5", "Rocks") %>
    <%= f.radio_button(:value, "4") %> <%= f.label(:value.to_s + "_4", "Pretty good") %>
    <%= f.radio_button(:value, "3") %> <%= f.label(:value.to_s + "_3", "Meh") %>
    <%= f.radio_button(:value, "2") %> <%= f.label(:value.to_s + "_2", "Kinda bad") %>
    <%= f.radio_button(:value, "1") %> <%= f.label(:value.to_s + "_1", "Sucks big time") %>
  </fieldset>
  <br><br>

  <h4>Cleanliness</h4>
  <fieldset class="rating">
    <%= f.radio_button(:cleanliness, "5") %> <%= f.label(:cleanliness.to_s + "_5", "Rocks") %>
    <%= f.radio_button(:cleanliness, "4") %> <%= f.label(:cleanliness.to_s + "_4", "Pretty good") %>
    <%= f.radio_button(:cleanliness, "3") %> <%= f.label(:cleanliness.to_s + "_3", "Meh") %>
    <%= f.radio_button(:cleanliness, "2") %> <%= f.label(:cleanliness.to_s + "_2", "Kinda bad") %>
    <%= f.radio_button(:cleanliness, "1") %> <%= f.label(:cleanliness.to_s + "_1", "Sucks big time") %>
  </fieldset>
  <br><br><br>

  <h4>Description of Job</h4>
  <%= f.number_field(:freelancer_id, {:style => 'display:none', :value => @freelancer.id}) %>

  <p>
    <%= f.text_field(:description_of_job, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/partials/_form_for_ratings.html.erb
<%= form_for :rating, url:"#", html: { method: :post } do |f| %>
  <fieldset class="rating_read_only">
    <% 5.downto(1) do |btn| %>
      <% if big_rating.to_i == btn %>
      <%= f.radio_button(:rating, "#{btn}", options = {checked: true}) %> <%= f.label(:rating.to_s + "_#{btn}", "egs") %>
      <% else %>
      <%= f.radio_button(:rating, "#{btn}", options = {disabled: true}) %> <%= f.label(:rating.to_s + "_#{btn}", "egs") %>
      <% end %>
    <% end %>
  </fieldset>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <%= link_to image_tag("logo2.png", alt: "logo", style:"height:25px;width:25px"), '/', class: 'navbar-brand' %>
            <%= link_to 'Matchee', root_path, class:"navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <% if current_freelancer %>
                 <ul class="nav navbar-nav">

                   <li><%= link_to 'Booking', bookings_index_path%></li>
                   <li><%= link_to 'My Enquiries', enquiries_path%></li>
                   <li class='dropdown'>
                     <a href="#" class="dropdown-toggle text-center notification" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Messages</a>

                     <ul class="dropdown-menu" id='notification-content'>
                       <% current_user.enquiries.each do |enquiry| %>
                         <% if enquiry.messages.where('sender_id !=? AND read =?', current_user.id, false).size > 0 %>
                           <li><%= link_to enquiry.description, edit_enquiry_path(enquiry) %></li>
                         <% end %>
                       <% end %>
                     </ul>
                   </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= cl_image_tag(current_freelancer.picture,
                            :width => 30, :height => 30,
                            :crop => :fill, :gravity => :face)
                            %></a>
                      <ul class="dropdown-menu">
                        <li><%= link_to 'Profile', profile_path(current_freelancer.id) %></li>
                        <li><%= link_to 'Edit Profile', edit_profile_path(current_freelancer.id) %></li>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
                      </ul>
                    </li>
                  </ul>


                  <% else %>
                  <li><%= link_to 'Become a Freelancer', new_profile_path %></li>
                  <ul class="nav navbar-nav">

                      <li class='dropdown'>
                        <a href="#" class="dropdown-toggle text-center notification" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Messages</a>

                        <ul class="dropdown-menu" id='notification-content'>
                          <% current_user.enquiries.each do |enquiry| %>
                            <% if enquiry.messages.where('sender_id !=? AND read =?', current_user.id, false).size > 0 %>
                              <li><%= link_to enquiry.description, edit_enquiry_path(enquiry) %></li>
                            <% end %>
                          <% end %>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle text-center" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= cl_image_tag(current_user.profile_picture,
                              :width => 30, :height => 30,
                              :crop => :thumb, :gravity => :face, :radius => :max)
                              %></a>

                        <ul class="dropdown-menu">
                          <li><%= link_to 'Profile', user_path(current_user.id) %></li>
                          <li><%= link_to 'Edit Profile', edit_user_path(current_user.id) %></li>
                          <li role="separator" class="divider"></li>
                          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
                        </ul>
                      </li>
                    </ul>
                  <% end %>
              <% else %>
                <li><%= link_to 'Login/Signup', login_path %></a></li>
              <% end %>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->

</nav>





<script>
$('.dropdown-toggle').dropdown()
</script>

app/views/partials/_search.html.erb
<div class="input-group input-group-lg col-md-8 col-md-offset-2">
    <%= form_tag profile_index_path, method: 'GET' do %>
      <%= text_field_tag :search, params[:search] , class:'col-md-8'%>
      <%= button_tag  name: nil , class:'btn btn-secondary col-md-3' do %>
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
      <% end %>
    <% end %>
  </div>