config/routes.rb
Rails.application.routes.draw do
  root 'freelancers#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  match 'logout' => 'sessions#destroy', via: [:get, :delete]
  post 'signup' => 'users#create'

  resources :users, only: [:edit, :update, :show]
  resources :email_confirmations, only: [:show, :index]
  resources :password_reset, only: [:show, :update, :create]
  resources :ratings, only: [:create, :show]


  get 'bookings/index'
  post 'bookings/create'






  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :freelancers, only: [:show, :new, :update, :edit, :create, :index], as: 'profile' do |f|
    resources :enquiries, only: [:new]
  end

  # resources :freelancers, only: [:show, :new, :update, :edit, :create, :index], as: 'restricted' do |f|
  #   resources :booking
  # end


  resources :enquiries,except: [:new]
  resources :ratings, only: [:show,:create]


  mount ActionCable.server, at: '/cable'


end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
  belongs_to :user
  belongs_to :freelancer
  has_many :messages

  before_save :default_enquiry_time_range, :if => :check_time_range
  before_update :default_enquiry_time_range, :if => :check_time_range

  # BOOKABLE GEM (ANDREW)
  acts_as_booker

  def check_time_range

    if self.start_date == nil && self.start_date == nil
      return true
    else
      return false
    end
  end

  def default_enquiry_time_range

    self.start_date = self.created_at.to_time.utc
    self.end_date = self.created_at.to_time.utc
  end

#   after_create :deliver
#
# @@REMINDER_TIME = 30.minutes # minutes before appointment
#
# # Notify our appointment attendee X minutes before the appointment time
# def deliver
#   @client = Twilio::REST::Client.new TWILIO_CONFIG['sid'], TWILIO_CONFIG['token']
#   message = @client.account.messages.create(:body => "Appointment msg",
#       :to => current_user.phone,    # Replace with your phone number
#       :from => TWILIO_CONFIG['from'])  # Replace with your Twilio number
#
#   puts "message entered"
# end
# #
# # def when_to_run
# #   time - @@REMINDER_TIME
# # end
#
# handle_asynchronously :deliver, :run_at => Proc.new { 30.minutes.from_now }

  def opposed_user(current)
    if current == freelancer.user
          user
    else
         freelancer.user
    end
  end

  def check_update(params)
    changes = {}
    params.each_pair do |key, value|
      if key == 'start_date' || key == 'end_date'
        changes[key] = value if self[key].to_time != value.to_time
      elsif key == 'price'

        changes[key] = value if self[key].to_s != value.to_s
      else
        changes[key] = value if self[key] != value
      end
    end
    changes
  end

  def send_auto_message(changes, user)
    content  = ' '
    changes.each_pair do |key, value|
      if key == 'start_date'
          name = "Start Date"
          render_value = value.to_date.to_s + ' ' + value.to_datetime.hour.to_s + ':' + value.to_datetime.minute.to_s
      elsif key == 'end_date'
        name = "End Date"
        render_value = value.to_date.to_s + ' ' + value.to_datetime.hour.to_s + ':' + value.to_datetime.minute.to_s
      else
         name = key
         render_value = value
      end


      content = content + '<br>' + name.capitalize + ':<strong> '+ render_value + '</strong>'
    end
    self.messages.create!(content: "#{content} <br> Changed ", sender_id: user)

    ActionCable.server.broadcast(
      "enquiry_channel_#{self.freelancer.user.id}",
      changes: changes,
      enquiry_id: self.id,
    )
  end

end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]
  before_action :is_authenticated, only: [:index, :edit, :update, :destroy]


  def index
    # @enquiries = Enquiry.where("user_id=?", @current_user.id)
    @enquiries = Enquiry.where("user_id =?", current_user.id)
    @freelancers = Freelancer.all
  end

  def show
    redirect_to signup_path  if @enquiry.user_id != current_user.id && @enquiry.freelancer.user_id != current_user.id
    @occurrences = {
       dates: @enquiry.freelancer.schedule.occurrences_between(Date.today - 1.year,Date.today + 1.year),
       start_time: @enquiry.freelancer.schedule.start_time.strftime("%I:%M%p"),
       end_time: @enquiry.freelancer.schedule.end_time.strftime("%I:%M%p"),
       start_date: @enquiry.start_date
     }
  end

  def edit
    if @enquiry.user_id != current_user.id && @enquiry.freelancer.user.id != current_user.id
      flash[:danger] = 'No access rights'
      redirect_to root_path
    end

    @occurrences = {
       dates: @enquiry.freelancer.schedule.occurrences_between(Date.today - 1.year,Date.today + 1.year),
       start_time: @enquiry.freelancer.schedule.start_time.strftime("%I:%M%p"),
       end_time: @enquiry.freelancer.schedule.end_time.strftime("%I:%M%p"),
       start_date: @enquiry.start_date
     }
    Message.clear_unread(@enquiry.messages, current_user)

  end

  def new
    @enquiry = Enquiry.new
    @freelancer = Freelancer.find(params[:profile_id])
    @occurrences = {
      dates: @freelancer.schedule.occurrences_between(Date.today - 1.year,Date.today + 1.year),
      start_time: @freelancer.schedule.start_time.strftime("%I:%M%p"),
      end_time: @freelancer.schedule.end_time.strftime("%I:%M%p")
    }
    puts "freelancer id is #{@freelancer.id}"
  end

  def create
    enquiry = Enquiry.where('freelancer_id =? AND status = ? AND user_id =? ', enquiry_params[:freelancer_id], 'open', current_user.id)

    if enquiry.size > 0
      flash[:danger] = "Can't create"
      redirect_to root_path
    else



    @enquiry = Enquiry.new(enquiry_params)
    @enquiry.user_id = current_user.id
    # @freelancer = Freelancer.find(params[:profile_id])
    # @enquiry.freelancer_id = @freelancer.id

    @enquiry.save!
      redirect_to enquiry_path(@enquiry), notice: 'Enquiry was successfully created.'
    end
  end

  def update
    respond_to do |format|
      changes = @enquiry.check_update(enquiry_params)
      if @enquiry.update(enquiry_params)
        @enquiry.send_auto_message(changes, current_user.id) if changes.size > 0
        format.html { redirect_to edit_enquiry_path(@enquiry), notice: 'Enquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry }
      else
        format.html { render :edit }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_enquiry
    @enquiry = Enquiry.find(params[:id])
  end

  def enquiry_params
    params.require(:enquiry).permit(:name, :description, :start_date, :end_date, :user_id, :freelancer_id, :price, :status, :id)
  end

end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_new.html.erb
<div class='col-md-12 '>

  <h3 class='text-center'>Enquiry Request</h3>
<%= form_for(@enquiry) do |f| %>
  <% if @enquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enquiry.errors.count, "error") %> prohibited this enquiry from being saved:</h2>
      <ul>
      <% @enquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, {:class => 'form-control'} %>
    </div>
  <br>
  <br>
    <div class="field">
    <%= f.label :start_date %>
    <%= f.datetime_field :start_date, {:class => 'form-control'}%>
  </div>
  <br>
  <br>
    <div class="field">
    <%= f.label :end_date %>
    <%= f.datetime_field :end_date, {:class => 'form-control'} %>
    </div>
  <br>
  <br>
    <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price, {:class => 'form-control'} %>
    </div>
  <br>
  <br>
    <%= f.hidden_field :freelancer_id, :value => @freelancer.id %>
  <div class="actions">
    <%= f.submit({:class => 'btn btn-primary form-control'}) %>
  </div>
<% end %>
</div>

app/views/enquiries/edit.html.erb
<div class='container'>
  <% if current_freelancer != nil %>
    <% if current_freelancer.id == @enquiry.freelancer.id %>
    <div class='row'>
    <div class='col-md-1'>
      <span>
        <%= cl_image_tag(@enquiry.user.profile_picture,
          :width => 80, :height => 80,
          :crop => :fill, :gravity => :face)
          %>
      </span>
    </div>

    <div class='col-md-offset-1'>
        <%= link_to @enquiry.user.name.capitalize, edit_enquiry_path(@enquiry.id),  class:'h2' %>
        <br>
        Requestor
    </div>
  </div>
  <% end %>


  <% else %>

  <div class='row'>
    <div class='col-md-1'>
      <span>
        <%= cl_image_tag(@enquiry.freelancer.picture,
            :width => 80, :height => 80,
            :crop => :fill, :gravity => :face)
            %>
      </span>
    </div>

    <div class='col-md-offset-1'>
        <%= link_to @enquiry.freelancer.user.name.capitalize, profile_path(@enquiry.freelancer.id) , class:'h2'%>
        <br>
        Freelancer
    </div>
  </div>
  <% end %>


  <br>
  <br>
  <br>



  <div class='row'>
    <div class='col-md-12'>
      <div class='col-md-5 enquiry_form panel panel-default'>
        <% if @enquiry.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(enquiry.errors.count, "error") %> prohibited this enquiry from being saved:</h2>
            <ul>
              <% @enquiry.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>






        <% if current_freelancer != nil %>
          <% if current_freelancer.id == @enquiry.freelancer.id %>
            <div class='row'>
              <div class='col-md-12'>
                <%= bootstrap_form_for(@enquiry, url: bookings_create_path, html: {method: "POST"})do |f| %>
                  <div class="field">

                    <%= f.text_field :description, class:"enquiry-"+ @enquiry.id.to_s + "-description", disabled: true %>
                    <%= f.hidden_field :description, class:"enquiry-"+ @enquiry.id.to_s + "-description" %>
                  </div>
                  <br>
                  <div class="field">

                    <%= f.datetime_field :start_date, class:"enquiry-"+@enquiry.id.to_s + "-start_date", disabled: true  %>
                    <%= f.hidden_field :start_date, class:"enquiry-"+@enquiry.id.to_s + "-start_date"  %>
                  </div>
                  <br>
                  <div class="field">

                    <%= f.datetime_field :end_date, class:"enquiry-"+@enquiry.id.to_s+ "-end_date", disabled: true  %>
                    <%= f.hidden_field :end_date, class:"enquiry-"+@enquiry.id.to_s+ "-end_date" %>
                  </div>
                  <br>
                  <div class="field">

                    <%= f.number_field :price, class:"enquiry-"+ @enquiry.id.to_s + "-price", disabled: true  %>
                    <%= f.hidden_field :price, class:"enquiry-"+ @enquiry.id.to_s + "-price" %>
                  </div>
                  <br>
                  <div class="field">
                    <%= f.hidden_field :id, {:class => 'form-control'} %>
                  </div>
                  <% if @enquiry.status != 'accepted' %>

                  <div class="actions">
                    <%= f.submit "Finalise  & Accept" ,class:'form-control btn btn-primary'%>
                  </div>
                  <% else %>
                  <%= f.submit "Deal Finalised" , class:'form-control btn btn-primary', disabled: true %>
                  <% end  %>



                </div>
                <%= render partial: 'partials/calendar_for_specific_booking', locals: { passed_datum: @occurrences } %>
            </div>
        <% end %>
<% end %>
  <% else %>
  <div class='row'>
    <div class='col-md-12'>
    <%= bootstrap_form_for(@enquiry, :html=>{:remote => true})do |f| %>

    <div class="field">

      <%= f.text_field :description, class:"enquiry-"+ @enquiry.id.to_s + "-description" %>
    </div>
    <br>
    <br>
    <div class="field">

      <%= f.datetime_field :start_date, class:"enquiry-"+@enquiry.id.to_s + "-start_date" %>
    </div>
    <br>
    <br>
    <div class="field">

      <%= f.datetime_field :end_date, class:"enquiry-"+@enquiry.id.to_s+ "-end_date" %>
    </div>
    <br>
    <br>
    <div class="field">

      <%= f.number_field :price, class:"enquiry-"+ @enquiry.id.to_s + "-price" %>
    </div>

    <% if @enquiry.status != 'accepted' %>

    <div class="actions">
      <%= f.submit "Update" , class:'form-control btn btn-primary' %>
    </div>
    <% else %>
    <%= f.submit "Deal Finalised" , class:'form-control btn btn-primary', disabled: true %>
    <% end  %>
  </div>
  <%= render partial: 'partials/calendar_for_specific_booking', locals: { passed_datum: @occurrences } %>
</div>
    <% end %>
  <% end %>
</div>


<div class='col-md-7'>
  <div id='messages' class='panel panel-default'>
    <%= render 'messages/message'%>
  </div>

  <form class="new_message" data-behavior="enquiry_speaker">
    <input name="read" type="hidden" value= false >
    <input name="enquiry_id" type="hidden" value="<%= @enquiry.id %>">
    <input name="sender_id" type="hidden" value="<%= current_user.id %>">
    <textarea name="content" class="form-control" ></textarea>
    <!-- <input type="submit" class="btn btn-success" value="Send"> -->
  </form>
</div>
</div>
</div>
</div>


<script>
var scrolled = false;
function updateScroll(){
    if(!scrolled){
        var element = document.getElementById("messages");
        element.scrollTop = element.scrollHeight;
    }
}

$("#messages").on('scroll', function(){
    scrolled=true;
});

updateScroll()
</script>

app/views/enquiries/index.html.erb
<div class='container'>


  <%= render 'partials/search' %>
  <h1>My Submitted Enquiries</h1>

  <% if @enquiries.length > 0  %>

  <table class='table'>
    <thead>
      <tr>
        <th>Description of Enquiry</th>
        <th>Enquiry's start date</th>
        <th>Enquiry's end date</th>
        <th>Liason</th>
      </tr>
    </thead>
    <% @enquiries.each do |enquiry| %>
    <tr>
      <td><%=enquiry.description%></td>
      <td><%=enquiry.start_date.strftime("%e %b %Y %l:%M %p")%></td>
      <td><%=enquiry.end_date.strftime("%e %b %Y %l:%M %p")%></td>
      <td><%= link_to raw("continue liason with <strong>#{enquiry.freelancer.user.name.capitalize}</strong>"), edit_enquiry_path(enquiry.id), {:class => 'btn btn-default'} %></td>
    </tr>
    <% end %>
  </table>

  <% else %>
    <div>
      <h1>You have not submitted any enquiry yet.</h1>
    </div>

  <% end %>
</div>

app/views/enquiries/show.html.erb
<div class='container'>
  <%= render 'partials/search' %>
  <div class='left'>
    <table class='table'>
      <tr>
        <thead>
          <tr>
            <th>Freelancer's name</th>
            <th>Description of the enquiry</th>
            <th>Job start date and time</th>
            <th>Job end date and time</th>
          </tr>
        </thead>
        <td><%=@enquiry.freelancer.user.name%></td>
        <td><%=@enquiry.description%></td>
        <td><%=@enquiry.start_date.strftime("%e %b %Y %l:%M %p")%></td>
        <td><%=@enquiry.end_date.strftime("%e %b %Y %l:%M %p")%></td>
      </tr>
    </table>
  </div>
  <div class='right'>
    <% if  !current_freelancer %>
    <h1>This is <%= @enquiry.freelancer.user.name %>'s schedule for the week <%=@enquiry.start_date.to_date.cweek%> of 2017 </h1>
    <% end %>
    <!-- testing out partial for weekly calendar ZL -->
    <!-- passed_datum requires :dates, :start_time, :end_time and start date and time slots as well later -->
    <%= render partial: 'partials/calendar_for_specific_booking', locals: { passed_datum: @occurrences } %>
    <% if @enquiry.status != 'done' %>
    <%= link_to "Chat", edit_enquiry_path(@enquiry), class:'btn btn-primary' %>
    <% end %>
  </div>
</div>